services:
  filmio-backend:
    build:
      context: .
      dockerfile: docker-prod.Dockerfile
    volumes:
      - './photos:/usr/src/app/photos'
    ports:
      - 8000:8000
    restart: unless-stopped
